In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
#from sklearn.metrics import mean_squared_error
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("telco_customer_churn.csv")
df.info()
df.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [3]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
#Identifying Categorical Variables among object datatypes
length_of_dataframe=len(df)
result=df.apply(lambda x:x.unique())
l=len(result)

list_index=result.index
i=0

categorical=[]
while i<l:
    if len(result.iloc[i])/length_of_dataframe < 0.01:
        categorical.append(list_index[i])
        print(list_index[i],len(result.iloc[i]))
    i+=1

gender 2
SeniorCitizen 2
Partner 2
Dependents 2
PhoneService 2
MultipleLines 3
InternetService 3
OnlineSecurity 3
OnlineBackup 3
DeviceProtection 3
TechSupport 3
StreamingTV 3
StreamingMovies 3
Contract 3
PaperlessBilling 2
PaymentMethod 4
Churn 2

In [5]:
df1=pd.get_dummies(df,columns=categorical,drop_first=True)
#df1.info()
custIDs=df1["customerID"]
df1.drop("customerID",axis=1,inplace=True)
def get_boolean_columns(df):
    c=list(df.columns)
    new_c=[]
    for col in c:
        if df[col].dtype=="bool":
            new_c.append(col)

    return new_c
#df1.select_dtypes(include=["bool"]).apply(lambda x: x.astype(int),inplace=True)
bool_columns=get_boolean_columns(df1)
df1.loc[:,bool_columns]=df1[bool_columns].astype(int)
print(df1["TotalCharges"].unique())
#df1["TotalCharges"] = df1["TotalCharges"].str.strip()  # remove all whitespace
#df1["TotalCharges"] = df1["TotalCharges"].replace("", np.nan)  # now replace empty strings

df1["TotalCharges"] = pd.to_numeric(df1["TotalCharges"], errors='coerce')
min_charge=df1["TotalCharges"].min()
max_charge=df1["TotalCharges"].max()
diff=max_charge-min_charge
df1["TotalCharges"]=(df["TotalCharges"]-min_charge)/diff
df1.dropna(inplace=True)
df1.loc[:,"TotalCharges"]=df1["TotalCharges"].astype(float)
df1.info()

['29.85' '1889.5' '108.15' ... '346.45' '306.6' '6844.5']

C:\Users\shash\AppData\Local\Temp\ipykernel_11136\3009079724.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0 1 1 ... 0 1 1]' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df1.loc[:,bool_columns]=df1[bool_columns].astype(int)
C:\Users\shash\AppData\Local\Temp\ipykernel_11136\3009079724.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0 0 0 ... 0 1 0]' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df1.loc[:,bool_columns]=df1[bool_columns].astype(int)
C:\Users\shash\AppData\Local\Temp\ipykernel_11136\3009079724.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[1 0 0 ... 1 1 0]' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df1.loc[:,bool_columns]=df1[bool_columns].astype(int)
C:\Users\shash\AppData\Local\Temp\ipykernel_11136\3009079724.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0 0 0 ... 1 0 0]' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df1.loc[:,bool_columns]=df1[bool_columns].astype(int)
C:\Users\shash\AppData\Local\Temp\ipykernel_11136\3009079724.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0 1 1 ... 0 1 1]' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df1.loc[:,bool_columns]=df1[bool_columns].astype(int)
C:\Users\shash\AppData\Local\Temp\ipykernel_11136\3009079724.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[1 0 0 ... 1 0 0]' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df1.loc[:,bool_columns]=df1[bool_columns].astype(int)
C:\Users\shash\AppData\Local\Temp\ipykernel_11136\3009079724.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0 0 0 ... 0 1 0]' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df1.loc[:,bool_columns]=df1[bool_columns].astype(int)
C:\Users\shash\AppData\Local\Temp\ipykernel_11136\3009079724.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0 0 0 ... 0 1 1]' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df1.loc[:,bool_columns]=df1[bool_columns].astype(int)
C:\Users\shash\AppData\Local\Temp\ipykernel_11136\3009079724.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0 0 0 ... 0 0 0]' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df1.loc[:,bool_columns]=df1[bool_columns].astype(int)
C:\Users\shash\AppData\Local\Temp\ipykernel_11136\3009079724.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0 0 0 ... 0 0 0]' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df1.loc[:,bool_columns]=df1[bool_columns].astype(int)
C:\Users\shash\AppData\Local\Temp\ipykernel_11136\3009079724.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0 1 1 ... 1 0 1]' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df1.loc[:,bool_columns]=df1[bool_columns].astype(int)
C:\Users\shash\AppData\Local\Temp\ipykernel_11136\3009079724.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0 0 0 ... 0 0 0]' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df1.loc[:,bool_columns]=df1[bool_columns].astype(int)
C:\Users\shash\AppData\Local\Temp\ipykernel_11136\3009079724.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[1 0 1 ... 0 0 0]' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df1.loc[:,bool_columns]=df1[bool_columns].astype(int)
C:\Users\shash\AppData\Local\Temp\ipykernel_11136\3009079724.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0 0 0 ... 0 0 0]' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df1.loc[:,bool_columns]=df1[bool_columns].astype(int)
C:\Users\shash\AppData\Local\Temp\ipykernel_11136\3009079724.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0 1 0 ... 0 0 1]' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df1.loc[:,bool_columns]=df1[bool_columns].astype(int)
C:\Users\shash\AppData\Local\Temp\ipykernel_11136\3009079724.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0 0 0 ... 0 0 0]' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df1.loc[:,bool_columns]=df1[bool_columns].astype(int)
C:\Users\shash\AppData\Local\Temp\ipykernel_11136\3009079724.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0 0 0 ... 0 0 1]' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df1.loc[:,bool_columns]=df1[bool_columns].astype(int)
C:\Users\shash\AppData\Local\Temp\ipykernel_11136\3009079724.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0 0 0 ... 0 0 0]' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df1.loc[:,bool_columns]=df1[bool_columns].astype(int)
C:\Users\shash\AppData\Local\Temp\ipykernel_11136\3009079724.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0 0 0 ... 0 0 1]' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df1.loc[:,bool_columns]=df1[bool_columns].astype(int)
C:\Users\shash\AppData\Local\Temp\ipykernel_11136\3009079724.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0 0 0 ... 0 0 0]' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df1.loc[:,bool_columns]=df1[bool_columns].astype(int)
C:\Users\shash\AppData\Local\Temp\ipykernel_11136\3009079724.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0 0 0 ... 0 0 1]' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df1.loc[:,bool_columns]=df1[bool_columns].astype(int)
C:\Users\shash\AppData\Local\Temp\ipykernel_11136\3009079724.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0 1 0 ... 0 0 0]' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df1.loc[:,bool_columns]=df1[bool_columns].astype(int)
C:\Users\shash\AppData\Local\Temp\ipykernel_11136\3009079724.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0 0 0 ... 0 0 1]' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df1.loc[:,bool_columns]=df1[bool_columns].astype(int)
C:\Users\shash\AppData\Local\Temp\ipykernel_11136\3009079724.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[1 0 1 ... 1 1 1]' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df1.loc[:,bool_columns]=df1[bool_columns].astype(int)
C:\Users\shash\AppData\Local\Temp\ipykernel_11136\3009079724.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0 0 0 ... 0 0 0]' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df1.loc[:,bool_columns]=df1[bool_columns].astype(int)
C:\Users\shash\AppData\Local\Temp\ipykernel_11136\3009079724.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[1 0 0 ... 1 0 0]' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df1.loc[:,bool_columns]=df1[bool_columns].astype(int)
C:\Users\shash\AppData\Local\Temp\ipykernel_11136\3009079724.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0 1 1 ... 0 1 0]' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df1.loc[:,bool_columns]=df1[bool_columns].astype(int)
C:\Users\shash\AppData\Local\Temp\ipykernel_11136\3009079724.py:15: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise in a future error of pandas. Value '[0 0 1 ... 0 1 0]' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df1.loc[:,bool_columns]=df1[bool_columns].astype(int)

TypeError: unsupported operand type(s) for -: 'str' and 'float'

In [ ]:

df1.head()

In [ ]:




model=LogisticRegression(max_iter=1000)
X=df1.drop("Churn_Yes",axis=1)
Y=df1["Churn_Yes"]

#print(X.isnull().sum())
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2)
model.fit(X_train,Y_train)
Y_pred=model.predict(X_test)

In [ ]:
from sklearn.metrics import roc_auc_score
def give_scores(tn,fp,fn,tp):
    precision=tp/(tp+fp)
    accuracy=tp/(tp+fp+fn+tn)
    recall=(tp+tn)/(tp+fp+fn+tn)
    f1=2*(precision*recall)/(precision+recall)
    return precision,accuracy,recall,f1
from sklearn.metrics import ConfusionMatrixDisplay
#print(len(Y_test),len(Y_pred))
ConfusionMatrixDisplay.from_predictions(Y_test,Y_pred)

In [ ]:
Y_proba=model.predict_proba(X_test)[:,1]
print(roc_auc_score(Y_test, Y_proba))
print(give_scores(956,86,177,188))

In [ ]:
#Logistic regression ROC AUC Curve is high, so the model was good enough , now i will try XGBoost
import xgboost as xgb
model1=xgb.XGBClassifier(use_label_encoder=False,eval_metric="mlogloss")
model1.fit(X_train,Y_train)
Y_pred=model1.predict(X_test)
ConfusionMatrixDisplay.from_predictions(Y_test,Y_pred)

In [ ]:
Y_proba=model.predict_proba(X_test)[:,1]
print(roc_auc_score(Y_test, Y_proba))
print(give_scores(956,86,177,188))

In [ ]:
#Logistic regression model performed better here than XGBoost
coefficients=model.coef_[0]
coeff=list(coefficients)
columns=list(X_train.columns)

imp_df=pd.DataFrame({"Features":columns,
              "Importance":coeff,
                    "Absolute_Features":[abs(i) for i in coeff]})

imp_df["Absolute_Features"]=imp_df["Absolute_Features"]*100/sum(imp_df["Absolute_Features"])
sorted_imp_df=imp_df.sort_values(by="Importance")
print(sorted_imp_df)
plt.bar(sorted_imp_df["Features"],sorted_imp_df["Importance"],color="blue")
plt.xlabel("Features")
plt.ylabel("Importance")

In [ ]:
"""
Conclusions:-
1)Contracts lasting as long as 2 year significantly reduces probability of churning of the customer
2)Fiber Optic internet service has a higher probability of the customer being churned
3)Tech Support and Phone service also reduce the churning probability of the customer
"""

In [ ]:
print(df.groupby("TechSupport")["Churn"].value_counts())

In [ ]:
#As we can see, for tech support being available to customers , the number of people who churned(310) are significantly less compared to who didnt (1734)

print(df.groupby("PhoneService")["Churn"].value_counts())

In [ ]:
#Churn rate for both the options of phone service is about the same , 170*100/(512+170) = 24.93% , and 1699*100/(4662+1699)=26.70%
#PhoneService not a viable feature here

print(df.groupby("InternetService")["Churn"].value_counts())

In [ ]:
#Churn rate for DSL=18.96,Fiber Optic=41.89,No internet service=7.41
#Fiber Optic Internet connection leads to a churn rate of 41.89 which is not good compared to churn rates of other internet service options